{
 "title": "My dashboard",
 "tags": [ "linux" ],
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   { "name": "DS_PROMETHEUS", "label": "datasource", "query": "prometheus" },
   {
    "name": "job",
    "label": "Job",
    "query": {
     "query": "label_values(node_uname_info, job)"
    }
   },
   {
    "name": "node",
    "label": "Host:",
    "query": {
     "query": "label_values(node_uname_info{job=\"$job\"}, instance)"
    }
   },
   { "name": "diskdevices" }
  ]
 },
 "panels": [
  {
   "title": "Количество свободной оперативной памяти",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "node_memory_MemFree_bytes{instance=\"$node\",job=\"$job\"}"
    }
   ]
  },
  {
   "title": "Количество места на файловой системе (всего)",
   "type": "stat",
   "gridPos": { "h": 9, "w": 5, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_filesystem_size_bytes{device=\"/dev/vda2\",fstype=\"ext4\",instance=\"$node\",job=\"$job\",mountpoint=\"/\"}"
    }
   ]
  },
  {
   "title": "Количество места на файловой системе (свободно)",
   "type": "stat",
   "gridPos": { "h": 9, "w": 5, "x": 17, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_filesystem_free_bytes{device=\"/dev/vda2\",fstype=\"ext4\",instance=\"$node\",job=\"$job\",mountpoint=\"/\"}"
    }
   ]
  },
  {
   "title": "Утилизация CPU для nodeexporter (в процентах, 100-idle)",
   "type": "timeseries",
   "description": "Утилизация CPU для nodeexporter (в процентах, 100-idle)",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "100 * (1 - avg by(instance)(irate(node_cpu_seconds_total{cpu=\"0\",instance=\"$node\",job=\"$job\",mode=\"idle\"}[5m])))"
    }
   ]
  },
  {
   "title": "CPULA 1/5/15",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 9 },
   "targets": [
    {
     "expr": "node_load1{instance=\"$node\",job=\"$job\"}",
     "legendFormat": "LA 1"
    },
    {
     "expr": "node_load5{instance=\"$node\",job=\"$job\"}",
     "legendFormat": "LA 5"
    },
    {
     "expr": "node_load15{instance=\"$node\",job=\"$job\"}",
     "legendFormat": "LA 15"
    }
   ]
  },
  {
   "title": "Количество места на файловой системе (свободно)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 6, "x": 16, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "node_filesystem_free_bytes{device=\"/dev/vda2\",fstype=\"ext4\",instance=\"10.128.0.24:9100\",job=\"node_1\",mountpoint=\"/\"}"
    }
   ]
  }
 ]
}